import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
export class Galaxy {
 constructor(host){
  this.host=host;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.05,350);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setClearColor(0x17143c);this.renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(this.renderer.domElement);this.focusImage=document.createElement('img');this.focusImage.className='focused-galaxy-photo';this.focusImage.alt='Ảnh đang xem phóng lớn';this.focusImage.hidden=true;this.focusImage.onclick=()=>{if(this.photoFocusIndex>=0)this.togglePhoto(this.photoFocusIndex)};this.focusImage.onerror=()=>{this.focusImage.hidden=true};host.append(this.focusImage);this.controls=new OrbitControls(this.camera,this.renderer.domElement);Object.assign(this.controls,{enableDamping:true,dampingFactor:.06,minDistance:3,maxDistance:95,enablePan:false,rotateSpeed:.5,zoomSpeed:.7});this.camera.position.set(0,1.2,12);this.controls.update();this.clock=new THREE.Clock();this.open=false;this.fly=0;this.disposed=false;this.dynamic=new THREE.Group();this.scene.add(this.dynamic);this.photoFocus=null;this.photoFocusIndex=-1;this.photoCenters=[];this.photoSizes=[];this.heartBursts=[];this.heartTexture=null;this.nextHeart=0;this.focusMode=false;this.planetGlow=null;this.pointerDown=null;this.createSpace();this.createPlanet();this.resize=()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)};addEventListener('resize',this.resize);this.resize();this.controls.addEventListener('start',()=>{this.fly=0;this.hideHint()});this.photoPointerDown=e=>{this.pointerDown={x:e.clientX,y:e.clientY}};this.photoPointerUp=e=>{if(!this.pointerDown)return;const moved=Math.hypot(e.clientX-this.pointerDown.x,e.clientY-this.pointerDown.y);this.pointerDown=null;if(moved<8)this.pickPhoto(e.clientX,e.clientY)};this.renderer.domElement.addEventListener('pointerdown',this.photoPointerDown);this.renderer.domElement.addEventListener('pointerup',this.photoPointerUp);this.animate();
 }
 createSpace(){
 const nebula=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{time:{value:0}},vertexShader:`varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`precision highp float;varying vec3 p;uniform float time;float hash(vec3 q){q=fract(q*.3183099+vec3(.1,.2,.3));q*=17.;return fract(q.x*q.y*q.z*(q.x+q.y+q.z));}float noise(vec3 q){vec3 i=floor(q),f=fract(q);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 q){float f=0.,a=.5;for(int i=0;i<5;i++){f+=a*noise(q);q=q*2.03+7.2;a*=.5;}return f;}void main(){vec3 q=normalize(p)*3.;float n=fbm(q*1.8);float cloud=smoothstep(.24,.78,n);vec3 col=mix(vec3(.60,.22,.43),vec3(.38,.25,.62),smoothstep(-.5,.9,sin(q.x*1.8+q.z)));col=mix(col,vec3(.65,.34,.53),smoothstep(.1,.9,sin(q.y*2.2-q.x)));col=mix(col,vec3(.90,.53,.57),pow(max(0.,sin(q.z*2.+q.y)),12.)*.85);gl_FragColor=vec4(vec3(.038,.018,.065)+col*cloud*.42,1.);}`});this.nebula=nebula;this.scene.add(new THREE.Mesh(new THREE.SphereGeometry(140,40,28),nebula));
 const positions=[],colors=[];for(let i=0;i<7200;i++){let a=Math.random()*Math.PI*2,z=Math.random()*2-1,r=34+Math.random()*72,s=Math.sqrt(1-z*z);positions.push(r*s*Math.cos(a),r*z,r*s*Math.sin(a));let t=.86+Math.random()*.14;colors.push(t,t*.96,Math.min(1,t+Math.random()*.12))}let geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));this.stars=new THREE.Points(geo,new THREE.PointsMaterial({size:.29,vertexColors:true,transparent:true,opacity:.98,sizeAttenuation:true,depthWrite:false}));this.scene.add(this.stars);const focusPositions=[],focusColors=[];for(let i=0;i<2600;i++){let a=Math.random()*Math.PI*2,z=Math.random()*2-1,r=18+Math.random()*92,s=Math.sqrt(1-z*z);focusPositions.push(r*s*Math.cos(a),r*z,r*s*Math.sin(a));let b=.78+Math.random()*.22;focusColors.push(b,b*(.78+Math.random()*.2),1)}let focusGeo=new THREE.BufferGeometry();focusGeo.setAttribute('position',new THREE.Float32BufferAttribute(focusPositions,3));focusGeo.setAttribute('color',new THREE.Float32BufferAttribute(focusColors,3));this.focusStars=new THREE.Points(focusGeo,new THREE.PointsMaterial({size:.22,vertexColors:true,transparent:true,opacity:.95,sizeAttenuation:true,depthWrite:false}));this.focusStars.visible=false;this.scene.add(this.focusStars);this.meteors=[];this.nextMeteor=5;this.scene.add(this.camera);
 const meteorGeo=new THREE.BufferGeometry();meteorGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,-3.6,.08,0],3));meteorGeo.setAttribute('color',new THREE.Float32BufferAttribute([1,1,1,.16,.12,.25],3));
 const meteor=new THREE.Line(meteorGeo,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:0,depthTest:true,depthWrite:false,blending:THREE.AdditiveBlending}));meteor.visible=false;meteor.renderOrder=10;this.camera.add(meteor);this.meteors.push({line:meteor,start:-10});

 }
 createPlanet(){this.sphereMaterial=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:`varying vec3 n;varying vec3 v;varying vec3 pos;void main(){pos=position;n=normalize(normalMatrix*normal);vec4 p=modelViewMatrix*vec4(position,1.);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}`,fragmentShader:`precision highp float;varying vec3 n;varying vec3 v;varying vec3 pos;uniform float time;void main(){float wave=sin(pos.y*2.7+pos.x*1.4+time*.25)+.4*sin(pos.z*4.-time*.2);vec3 pink=vec3(1.,.64,.79),purple=vec3(.72,.62,.94),green=vec3(.63,.92,.86);vec3 color=mix(purple,pink,smoothstep(-1.,.9,wave));color=mix(color,green,pow(smoothstep(.55,1.35,sin(pos.x*2.1-pos.y*2.+time*.15)),2.)*.85);float fres=pow(1.-abs(dot(normalize(n),normalize(v))),2.6);color+=vec3(.38,.23,.38)*fres;float light=.75+.25*max(0.,dot(normalize(n),normalize(vec3(-.6,.8,1.))));color*=light;color+=pow(max(0.,dot(reflect(-normalize(vec3(-.4,.6,1.)),normalize(n)),normalize(v))),22.)*.24;gl_FragColor=vec4(color,1.);}`});this.planet=new THREE.Mesh(new THREE.SphereGeometry(1.3,64,48),this.sphereMaterial);this.scene.add(this.planet);
 let glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=128;let c=glowCanvas.getContext('2d'),g=c.createRadialGradient(64,64,26,64,64,64);g.addColorStop(0,'#e99fff55');g.addColorStop(.5,'#ce65f82b');g.addColorStop(1,'#9c43dd00');c.fillStyle=g;c.fillRect(0,0,128,128);let sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));sprite.scale.set(4.3,4.3,1);this.planetGlow=sprite;this.scene.add(sprite);
 }
 makeHeartTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d');c.font='bold 104px Arial';c.textAlign='center';c.textBaseline='middle';c.shadowColor='#ff7fbe';c.shadowBlur=15;c.fillStyle='#ffd2e8';c.fillText('♥',64,68);return new THREE.CanvasTexture(canvas)}
 async configure(data){this.open=false;this.dynamic.visible=false;this.reset();this.dynamic.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}});this.dynamic.clear();this.phraseRings=[];this.photoCloud=null;this.photoFocusIndex=-1;this.heartBursts=[];
 const urls=data.images||[];let atlas=document.createElement('canvas');atlas.width=atlas.height=1024;let ctx=atlas.getContext('2d');let loaded=await Promise.all(urls.map(url=>new Promise(resolve=>{let im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=url})));loaded=loaded.filter(Boolean);this.loadedPhotos=loaded;let grid=Math.ceil(Math.sqrt(Math.max(1,loaded.length))),cell=1024/grid;
 loaded.forEach((im,i)=>{let x=(i%grid)*cell,y=Math.floor(i/grid)*cell;ctx.save();ctx.beginPath();ctx.roundRect(x+3,y+3,cell-6,cell-6,cell*.065);ctx.clip();ctx.fillStyle='#fff';ctx.fillRect(x,y,cell,cell);let side=Math.min(im.width,im.height);ctx.drawImage(im,(im.width-side)/2,(im.height-side)/2,side,side,x+6,y+6,cell-12,cell-12);ctx.restore()});
 const texture=new THREE.CanvasTexture(atlas);texture.colorSpace=THREE.SRGBColorSpace;let count=loaded.length?560:1200,positions=[],sizes=[],indices=[],colors=[];for(let i=0;i<count;i++){let theta=i*2.3999632297,r=Math.sqrt(8*8+(i+.5)/count*(33*33-8*8));positions.push(Math.cos(theta)*r,(Math.random()-.5)*(.6+r*.16),Math.sin(theta)*r);sizes.push(loaded.length?(.24+Math.random()**2*.50):(.025+Math.random()*.05));indices.push(i%Math.max(1,loaded.length));colors.push(.65+Math.random()*.35,.65+Math.random()*.35,1)}this.photoCenters=positions;this.photoSizes=sizes;this.photoFocus=new Float32Array(count);const plane=new THREE.PlaneGeometry(1,1);
 const geo=new THREE.InstancedBufferGeometry();geo.index=plane.index.clone();geo.setAttribute('position',plane.attributes.position.clone());geo.setAttribute('uv',plane.attributes.uv.clone());plane.dispose();
 geo.setAttribute('center',new THREE.InstancedBufferAttribute(new Float32Array(positions),3));geo.setAttribute('size',new THREE.InstancedBufferAttribute(new Float32Array(sizes),1));geo.setAttribute('tile',new THREE.InstancedBufferAttribute(new Float32Array(indices),1));geo.setAttribute('color',new THREE.InstancedBufferAttribute(new Float32Array(colors),3));geo.setAttribute('focus',new THREE.InstancedBufferAttribute(this.photoFocus,1));geo.instanceCount=count;
 const mat=new THREE.ShaderMaterial({uniforms:{atlas:{value:texture},grid:{value:grid},usePhotos:{value:loaded.length?1:0},farTint:{value:0},focusMode:{value:0}},transparent:false,depthTest:true,depthWrite:true,toneMapped:false,
 vertexShader:`uniform float focusMode;attribute vec3 center;attribute float size;attribute float tile;attribute float focus;attribute vec3 color;varying float idx;varying vec3 tint;varying vec2 photoUv;void main(){idx=tile;tint=color;photoUv=uv;if(focusMode>.5&&focus<.5){gl_Position=vec4(2.,2.,2.,1.);return;}vec4 p;if(focusMode>.5&&focus>.5){p=vec4(0.,0.,-5.1,1.);p.xy+=position.xy*4.15;}else{p=modelViewMatrix*vec4(center,1.);p.xy+=position.xy*size*2.;}gl_Position=projectionMatrix*p;}`,
 fragmentShader:`uniform sampler2D atlas;uniform float grid;uniform float usePhotos;uniform float farTint;varying float idx;varying vec3 tint;varying vec2 photoUv;void main(){if(usePhotos>.5){vec2 cell=vec2(mod(idx,grid),floor(idx/grid));vec2 uv=(cell+vec2(photoUv.x,1.-photoUv.y))/grid;vec4 col=texture2D(atlas,vec2(uv.x,1.-uv.y));if(col.a<.5)discard;vec3 pastel=mix(vec3(1.,.64,.79),vec3(.63,.92,.86),fract(idx*.618));pastel=mix(pastel,vec3(.72,.62,.94),.25);float detail=.8+.2*dot(col.rgb,vec3(.2126,.7152,.0722));gl_FragColor=vec4(mix(col.rgb,pastel*detail,farTint),1.);}else{float a=1.-smoothstep(.1,.5,length(photoUv-.5));if(a<.2)discard;gl_FragColor=vec4(tint*a,1.);}
 #include <colorspace_fragment>
 }`});this.photoCloud=new THREE.Mesh(geo,mat);this.photoCloud.frustumCulled=false;this.dynamic.add(this.photoCloud);

 let phrases=data.phrases?.length?data.phrases:['Love'];phrases.forEach((phrase,j)=>{
 const orbit=new THREE.Group();orbit.rotation.set(.55+j*.70,.15+j*.28,-.35+j*.42);
 const ring=new THREE.Group();orbit.add(ring);const radius=1.85+j*.49;
 const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d');ctx.font='bold 64px Arial';
 canvas.width=Math.ceil(ctx.measureText(phrase+'  ♥  ').width)+30;canvas.height=100;
 ctx.font='bold 64px Arial';ctx.textBaseline='middle';ctx.fillStyle='#fff7fc';ctx.shadowColor='#f697d1';ctx.shadowBlur=3;ctx.fillText(phrase+'  ♥  ',15,50);
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=THREE.RepeatWrapping;
 const height=.23;const textWidth=canvas.width/canvas.height*height;const repeats=Math.max(1,Math.floor(2*Math.PI*radius/textWidth));texture.repeat.set(repeats,1);
 const vertices=[],uv=[],indices=[],segments=256;
 for(let k=0;k<=segments;k++){const a=k/segments*Math.PI*2;vertices.push(Math.cos(a)*radius,-height/2,Math.sin(a)*radius,Math.cos(a)*radius,height/2,Math.sin(a)*radius);uv.push(k/segments,0,k/segments,1);if(k<segments){const n=k*2;indices.push(n,n+1,n+2,n+1,n+3,n+2)}}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geometry.setIndex(indices);
 ring.add(new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide,transparent:true,alphaTest:.15,depthWrite:true})));
 this.dynamic.add(orbit);this.phraseRings.push(ring);
 });
 this.sphereMaterial.uniforms.time.value=0;this.photoCloud.rotation.y=0;return {loadedImages:loaded.length};
 }

 pickPhoto(x,y){if(!this.photoCloud||!this.photoCenters.length||!this.open)return;if(this.photoFocusIndex>=0){let half=Math.min(innerWidth,innerHeight)*.46;if(Math.abs(x-innerWidth/2)<=half&&Math.abs(y-innerHeight/2)<=half)this.togglePhoto(this.photoFocusIndex);return}this.photoCloud.updateMatrixWorld(true);let best=-1,bestScore=Infinity;for(let i=0;i<this.photoSizes.length;i++){let center=new THREE.Vector3(this.photoCenters[i*3],this.photoCenters[i*3+1],this.photoCenters[i*3+2]).applyMatrix4(this.photoCloud.matrixWorld),distance=this.camera.position.distanceTo(center),projected=center.clone().project(this.camera);if(projected.z<-1||projected.z>1)continue;let sx=(projected.x+1)*.5*innerWidth,sy=(1-projected.y)*.5*innerHeight,pixelSize=Math.max(14,this.photoSizes[i]*2*innerHeight/(2*Math.tan(THREE.MathUtils.degToRad(this.camera.fov)/2)*Math.max(.1,distance))),screenDistance=Math.hypot(x-sx,y-sy);if(screenDistance<pixelSize*.7+14){let score=screenDistance/pixelSize+distance*.0005;if(score<bestScore){best=i;bestScore=score}}}if(best>=0)this.togglePhoto(best)}
 togglePhoto(index){let same=this.photoFocusIndex===index;this.photoFocus.fill(0);this.photoCloud.geometry.attributes.focus.needsUpdate=true;if(same){this.photoFocusIndex=-1;this.setFocusMode(false);this.controls.enabled=true;this.clearHeartBursts();return}this.photoFocus[index]=1;this.photoFocusIndex=index;this.photoCloud.geometry.attributes.focus.needsUpdate=true;this.setFocusMode(true);this.controls.enabled=false;if(this.loadedPhotos?.length){this.focusImage.hidden=false;this.focusImage.src=this.loadedPhotos[index%this.loadedPhotos.length].src}this.nextMeteor=this.clock.getElapsedTime()+.35;this.nextHeart=this.clock.getElapsedTime();for(let i=0;i<5;i++)this.spawnFocusHeart(i*.12)}
 setFocusMode(active){this.focusMode=active;if(!active&&this.focusImage)this.focusImage.hidden=true;if(this.photoCloud?.material?.uniforms.focusMode)this.photoCloud.material.uniforms.focusMode.value=active?1:0;if(this.planet)this.planet.visible=!active;if(this.planetGlow)this.planetGlow.visible=!active;this.phraseRings?.forEach(r=>{r.visible=!active});if(this.focusStars)this.focusStars.visible=active}
 spawnFocusHeart(delay=0){let texture=this.heartTexture||(this.heartTexture=this.makeHeartTexture()),sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false,opacity:0,blending:THREE.AdditiveBlending})),startX=(Math.random()-.5)*4.6,startY=-3.8-Math.random()*.7,startZ=-4.3-Math.random()*.8,baseScale=.22+Math.random()*.2;sprite.position.set(startX,startY,startZ);this.camera.add(sprite);this.heartBursts.push({sprite,started:performance.now()+delay*1000,duration:2.1+Math.random()*.8,startX,startY,startZ,rise:3.1+Math.random()*1.8,drift:(Math.random()-.5)*.8,baseScale,wobble:Math.random()*Math.PI*2})}
 clearHeartBursts(){this.heartBursts.forEach(b=>{this.camera.remove(b.sprite);b.sprite.material.dispose()});this.heartBursts=[]}
 enter(){this.open=true;this.dynamic.visible=true;this.fly=1;this.flyStart=performance.now();this.startPosition=this.camera.position.clone();this.endPosition=new THREE.Vector3(0,3.7,21)}

 reset(){this.fly=0;this.photoFocusIndex=-1;if(this.photoFocus)this.photoFocus.fill(0);this.setFocusMode(false);this.controls.enabled=true;this.clearHeartBursts();this.camera.position.set(0,1.6,this.open?21:9.5);this.controls.target.set(0,0,0);this.controls.update()}
 hideHint(){if(!this.open)return;const hint=document.getElementById("sceneHint");if(hint)hint.hidden=true;try{sessionStorage.setItem("galaxy-hint-seen","1")}catch{}}
 zoom(factor){this.hideHint();this.fly=0;let len=THREE.MathUtils.clamp(this.camera.position.length()*factor,3,95);this.camera.position.setLength(len);this.controls.update()}
 animate=()=>{if(this.disposed)return;this.raf=requestAnimationFrame(this.animate);let t=this.clock.getElapsedTime();this.sphereMaterial.uniforms.time.value=t;if(this.photoCloud){this.photoCloud.rotation.y=t*.025;this.photoCloud.material.uniforms.farTint.value=THREE.MathUtils.smoothstep(this.camera.position.length(),38,58);}if(this.focusStars)this.focusStars.rotation.y=t*.008;this.phraseRings?.forEach((r,i)=>{r.rotation.y=t*(i%2?-.13:.13)});
 const m=this.meteors[0];if(this.open&&t>=this.nextMeteor){m.start=t;m.y=1.3+Math.random()*2.5;m.line.position.set(-7,m.y,-12);this.nextMeteor=t+7+Math.random()*7;}
 const age=t-m.start;if(this.open&&age>=0&&age<3.2){m.line.visible=true;m.line.position.x=-7+age/3.2*14;m.line.position.y=m.y-age*.12;m.line.material.opacity=Math.sin(age/3.2*Math.PI)}else m.line.visible=false;
 if(this.focusMode&&t>=this.nextHeart){this.spawnFocusHeart();this.nextHeart=t+.42}this.heartBursts=this.heartBursts.filter(b=>{let age=(performance.now()-b.started)/1000;if(age<0)return true;let progress=age/b.duration;if(progress>=1){this.camera.remove(b.sprite);b.sprite.material.dispose();return false}let wave=Math.sin(progress*Math.PI);b.sprite.position.set(b.startX+Math.sin(progress*Math.PI*2+b.wobble)*b.drift,b.startY+b.rise*progress,b.startZ);b.sprite.scale.setScalar(b.baseScale*(.75+wave*.35));b.sprite.material.opacity=Math.min(1,age*5)*(1-progress);return true});if(this.fly){let k=Math.min(1,(performance.now()-this.flyStart)/2200);k=k*k*(3-2*k);this.camera.position.lerpVectors(this.startPosition,this.endPosition,k);if(k>=1)this.fly=0}this.controls.update();this.renderer.render(this.scene,this.camera)}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.renderer.domElement.removeEventListener('pointerdown',this.photoPointerDown);this.renderer.domElement.removeEventListener('pointerup',this.photoPointerUp);this.controls.dispose();this.clearHeartBursts();this.scene.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}});this.heartTexture?.dispose();this.renderer.dispose();this.host.replaceChildren()}
}
